<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class AllianceNationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $allianceNationalities = [
            ['id' => '1', 'nationality' => 'Afghan', 'nationality_id' => '1'],
            ['id' => '2', 'nationality' => 'Albanian', 'nationality_id' => '2'],
            ['id' => '3', 'nationality' => 'Algerian', 'nationality_id' => '3'],
            ['id' => '4', 'nationality' => 'American', 'nationality_id' => '4'],
            ['id' => '5', 'nationality' => 'Andorran', 'nationality_id' => '5'],
            ['id' => '6', 'nationality' => 'Angolan', 'nationality_id' => '6'],
            ['id' => '7', 'nationality' => 'Antiguans', 'nationality_id' => '7'],
            ['id' => '8', 'nationality' => 'Argentinean', 'nationality_id' => '8'],
            ['id' => '9', 'nationality' => 'Armenian', 'nationality_id' => '9'],
            ['id' => '10', 'nationality' => 'Australian', 'nationality_id' => '10'],
            ['id' => '11', 'nationality' => 'Austrian', 'nationality_id' => '11'],
            ['id' => '12', 'nationality' => 'Azerbaijani', 'nationality_id' => '12'],
            ['id' => '13', 'nationality' => 'Bahamian', 'nationality_id' => '13'],
            ['id' => '14', 'nationality' => 'Bahraini', 'nationality_id' => '14'],
            ['id' => '15', 'nationality' => 'Bangladeshi', 'nationality_id' => '15'],
            ['id' => '16', 'nationality' => 'Barbadian', 'nationality_id' => '16'],
            ['id' => '17', 'nationality' => 'Barbudans', 'nationality_id' => '17'],
            ['id' => '18', 'nationality' => 'Batswana', 'nationality_id' => '18'],
            ['id' => '19', 'nationality' => 'Belarusian', 'nationality_id' => '19'],
            ['id' => '20', 'nationality' => 'Belgian', 'nationality_id' => '20'],
            ['id' => '21', 'nationality' => 'Belizean', 'nationality_id' => '21'],
            ['id' => '22', 'nationality' => 'Beninese', 'nationality_id' => '22'],
            ['id' => '23', 'nationality' => 'Bhutanese', 'nationality_id' => '23'],
            ['id' => '24', 'nationality' => 'Bolivian', 'nationality_id' => '24'],
            ['id' => '25', 'nationality' => 'Bosnian', 'nationality_id' => '25'],
            ['id' => '26', 'nationality' => 'Brazilian', 'nationality_id' => '26'],
            ['id' => '27', 'nationality' => 'British', 'nationality_id' => '27'],
            ['id' => '28', 'nationality' => 'Bruneian', 'nationality_id' => '28'],
            ['id' => '29', 'nationality' => 'Bulgarian', 'nationality_id' => '29'],
            ['id' => '30', 'nationality' => 'Burkinabe', 'nationality_id' => '30'],
            ['id' => '31', 'nationality' => 'Burmese', 'nationality_id' => '31'],
            ['id' => '32', 'nationality' => 'Burundian', 'nationality_id' => '32'],
            ['id' => '33', 'nationality' => 'Cambodian', 'nationality_id' => '33'],
            ['id' => '34', 'nationality' => 'Cameroonian', 'nationality_id' => '34'],
            ['id' => '35', 'nationality' => 'Canadian', 'nationality_id' => '35'],
            ['id' => '36', 'nationality' => 'Cape Verdean', 'nationality_id' => '36'],
            ['id' => '37', 'nationality' => 'Central African', 'nationality_id' => '37'],
            ['id' => '38', 'nationality' => 'Chadian', 'nationality_id' => '38'],
            ['id' => '39', 'nationality' => 'Chilean', 'nationality_id' => '39'],
            ['id' => '40', 'nationality' => 'Chinese', 'nationality_id' => '40'],
            ['id' => '41', 'nationality' => 'Colombian', 'nationality_id' => '41'],
            ['id' => '42', 'nationality' => 'Comoran', 'nationality_id' => '42'],
            ['id' => '43', 'nationality' => 'Congolese', 'nationality_id' => '43'],
            ['id' => '44', 'nationality' => 'Costa Rican', 'nationality_id' => '44'],
            ['id' => '45', 'nationality' => 'Croatian', 'nationality_id' => '45'],
            ['id' => '46', 'nationality' => 'Cuban', 'nationality_id' => '46'],
            ['id' => '47', 'nationality' => 'Cypriot', 'nationality_id' => '47'],
            ['id' => '48', 'nationality' => 'Czech', 'nationality_id' => '48'],
            ['id' => '49', 'nationality' => 'Danish', 'nationality_id' => '49'],
            ['id' => '50', 'nationality' => 'Djiboutian', 'nationality_id' => '50'],
            ['id' => '51', 'nationality' => 'Dominican', 'nationality_id' => '51'],
            ['id' => '52', 'nationality' => 'Dutch', 'nationality_id' => '52'],
            ['id' => '53', 'nationality' => 'East Timorese', 'nationality_id' => '55'],
            ['id' => '54', 'nationality' => 'Ecuadorean', 'nationality_id' => '56'],
            ['id' => '55', 'nationality' => 'Egyptian', 'nationality_id' => '57'],
            ['id' => '56', 'nationality' => 'Emirati', 'nationality_id' => '198'],
            ['id' => '57', 'nationality' => 'Equatorial Guinean', 'nationality_id' => '59'],
            ['id' => '58', 'nationality' => 'Eritrean', 'nationality_id' => '60'],
            ['id' => '59', 'nationality' => 'Estonian', 'nationality_id' => '61'],
            ['id' => '60', 'nationality' => 'Ethiopian', 'nationality_id' => '62'],
            ['id' => '61', 'nationality' => 'Fijian', 'nationality_id' => '63'],
            ['id' => '62', 'nationality' => 'Filipino', 'nationality_id' => '64'],
            ['id' => '63', 'nationality' => 'Finnish', 'nationality_id' => '65'],
            ['id' => '64', 'nationality' => 'French', 'nationality_id' => '66'],
            ['id' => '65', 'nationality' => 'Gabonese', 'nationality_id' => '67'],
            ['id' => '66', 'nationality' => 'Gambian', 'nationality_id' => '68'],
            ['id' => '67', 'nationality' => 'Georgian', 'nationality_id' => '69'],
            ['id' => '68', 'nationality' => 'German', 'nationality_id' => '70'],
            ['id' => '69', 'nationality' => 'Ghanaian', 'nationality_id' => '71'],
            ['id' => '70', 'nationality' => 'Greek', 'nationality_id' => '72'],
            ['id' => '71', 'nationality' => 'Grenadian', 'nationality_id' => '73'],
            ['id' => '72', 'nationality' => 'Guatemalan', 'nationality_id' => '74'],
            ['id' => '73', 'nationality' => 'Guinea-Bissauan', 'nationality_id' => '75'],
            ['id' => '74', 'nationality' => 'Guinean', 'nationality_id' => '76'],
            ['id' => '75', 'nationality' => 'Guyanese', 'nationality_id' => '77'],
            ['id' => '76', 'nationality' => 'Haitian', 'nationality_id' => '78'],
            ['id' => '77', 'nationality' => 'Herzegovinian', 'nationality_id' => '79'],
            ['id' => '78', 'nationality' => 'Honduran', 'nationality_id' => '80'],
            ['id' => '79', 'nationality' => 'Hungarian', 'nationality_id' => '81'],
            ['id' => '80', 'nationality' => 'Kiribati', 'nationality_id' => '83'],
            ['id' => '81', 'nationality' => 'Icelandic', 'nationality_id' => '84'],
            ['id' => '82', 'nationality' => 'Indian', 'nationality_id' => '85'],
            ['id' => '83', 'nationality' => 'Indonesian', 'nationality_id' => '86'],
            ['id' => '84', 'nationality' => 'Iranian', 'nationality_id' => '87'],
            ['id' => '85', 'nationality' => 'Iraqi', 'nationality_id' => '88'],
            ['id' => '86', 'nationality' => 'Irish', 'nationality_id' => '89'],
            ['id' => '87', 'nationality' => 'Israeli', 'nationality_id' => '206'],
            ['id' => '88', 'nationality' => 'Italian', 'nationality_id' => '91'],
            ['id' => '89', 'nationality' => 'Ivorian', 'nationality_id' => '92'],
            ['id' => '90', 'nationality' => 'Jamaican', 'nationality_id' => '93'],
            ['id' => '91', 'nationality' => 'Japanese', 'nationality_id' => '94'],
            ['id' => '92', 'nationality' => 'Jordanian', 'nationality_id' => '95'],
            ['id' => '93', 'nationality' => 'Kazakhstani', 'nationality_id' => '96'],
            ['id' => '94', 'nationality' => 'Kenyan', 'nationality_id' => '97'],
            ['id' => '95', 'nationality' => 'Kittian and Nevisian', 'nationality_id' => '98'],
            ['id' => '96', 'nationality' => 'Kuwaiti', 'nationality_id' => '99'],
            ['id' => '97', 'nationality' => 'Kyrgyz', 'nationality_id' => '100'],
            ['id' => '98', 'nationality' => 'Laotian', 'nationality_id' => '101'],
            ['id' => '99', 'nationality' => 'Latvian', 'nationality_id' => '102'],
            ['id' => '100', 'nationality' => 'Lebanese', 'nationality_id' => '103'],
            ['id' => '101', 'nationality' => 'Liberian', 'nationality_id' => '104'],
            ['id' => '102', 'nationality' => 'Libyan', 'nationality_id' => '105'],
            ['id' => '103', 'nationality' => 'Liechtensteiner', 'nationality_id' => '106'],
            ['id' => '104', 'nationality' => 'Lithuanian', 'nationality_id' => '107'],
            ['id' => '105', 'nationality' => 'Luxembourger', 'nationality_id' => '108'],
            ['id' => '106', 'nationality' => 'Macedonian', 'nationality_id' => '109'],
            ['id' => '107', 'nationality' => 'Malagasy', 'nationality_id' => '110'],
            ['id' => '108', 'nationality' => 'Malawian', 'nationality_id' => '111'],
            ['id' => '109', 'nationality' => 'Malaysian', 'nationality_id' => '112'],
            ['id' => '110', 'nationality' => 'Maldivan', 'nationality_id' => '113'],
            ['id' => '111', 'nationality' => 'Malian', 'nationality_id' => '114'],
            ['id' => '112', 'nationality' => 'Maltese', 'nationality_id' => '115'],
            ['id' => '113', 'nationality' => 'Marshallese', 'nationality_id' => '116'],
            ['id' => '114', 'nationality' => 'Mauritanian', 'nationality_id' => '117'],
            ['id' => '115', 'nationality' => 'Mauritian', 'nationality_id' => '118'],
            ['id' => '116', 'nationality' => 'Mexican', 'nationality_id' => '119'],
            ['id' => '117', 'nationality' => 'Micronesian', 'nationality_id' => '120'],
            ['id' => '118', 'nationality' => 'Moldovan', 'nationality_id' => '121'],
            ['id' => '119', 'nationality' => 'Monacan', 'nationality_id' => '122'],
            ['id' => '120', 'nationality' => 'Mongolian', 'nationality_id' => '123'],
            ['id' => '121', 'nationality' => 'Moroccan', 'nationality_id' => '124'],
            ['id' => '122', 'nationality' => 'Mosotho', 'nationality_id' => '125'],
            ['id' => '123', 'nationality' => 'Motswana', 'nationality_id' => '126'],
            ['id' => '124', 'nationality' => 'Mozambican', 'nationality_id' => '127'],
            ['id' => '125', 'nationality' => 'Namibian', 'nationality_id' => '128'],
            ['id' => '126', 'nationality' => 'Nauruan', 'nationality_id' => '129'],
            ['id' => '127', 'nationality' => 'Nepalese', 'nationality_id' => '130'],
            ['id' => '128', 'nationality' => 'New Zealander', 'nationality_id' => '132'],
            ['id' => '129', 'nationality' => 'Ni-vanuatu', 'nationality_id' => '133'],
            ['id' => '130', 'nationality' => 'Nicaraguan', 'nationality_id' => '134'],
            ['id' => '131', 'nationality' => 'Nigerien', 'nationality_id' => '135'],
            ['id' => '132', 'nationality' => 'North Korean', 'nationality_id' => '136'],
            ['id' => '133', 'nationality' => 'Northern Irish', 'nationality_id' => '137'],
            ['id' => '134', 'nationality' => 'Norwegian', 'nationality_id' => '138'],
            ['id' => '135', 'nationality' => 'Omani', 'nationality_id' => '139'],
            ['id' => '136', 'nationality' => 'Pakistani', 'nationality_id' => '140'],
            ['id' => '137', 'nationality' => 'Palestinian', 'nationality_id' => '201'],
            ['id' => '138', 'nationality' => 'Palauan', 'nationality_id' => '141'],
            ['id' => '139', 'nationality' => 'Panamanian', 'nationality_id' => '142'],
            ['id' => '140', 'nationality' => 'Papua New Guinean', 'nationality_id' => '143'],
            ['id' => '141', 'nationality' => 'Paraguayan', 'nationality_id' => '144'],
            ['id' => '142', 'nationality' => 'Peruvian', 'nationality_id' => '145'],
            ['id' => '143', 'nationality' => 'Polish', 'nationality_id' => '146'],
            ['id' => '144', 'nationality' => 'Madeira', 'nationality_id' => ''],
            ['id' => '145', 'nationality' => 'Qatari', 'nationality_id' => '148'],
            ['id' => '146', 'nationality' => 'Romanian', 'nationality_id' => '149'],
            ['id' => '147', 'nationality' => 'Russian', 'nationality_id' => '150'],
            ['id' => '148', 'nationality' => 'Rwandan', 'nationality_id' => '151'],
            ['id' => '149', 'nationality' => 'Saint Lucian', 'nationality_id' => '152'],
            ['id' => '150', 'nationality' => 'Salvadoran', 'nationality_id' => '153'],
            ['id' => '151', 'nationality' => 'Samoan', 'nationality_id' => '154'],
            ['id' => '152', 'nationality' => 'Sammarinese', 'nationality_id' => '155'],
            ['id' => '153', 'nationality' => 'Sao Tomean', 'nationality_id' => '156'],
            ['id' => '154', 'nationality' => 'Saudi Arabian', 'nationality_id' => '157'],
            ['id' => '155', 'nationality' => 'Scottish', 'nationality_id' => '158'],
            ['id' => '156', 'nationality' => 'Senegalese', 'nationality_id' => '159'],
            ['id' => '157', 'nationality' => 'Serbian', 'nationality_id' => '160'],
            ['id' => '158', 'nationality' => 'Citizen of Seychelles', 'nationality_id' => '161'],
            ['id' => '159', 'nationality' => 'Sierra Leonean', 'nationality_id' => '162'],
            ['id' => '160', 'nationality' => 'Singaporean', 'nationality_id' => '163'],
            ['id' => '161', 'nationality' => 'Slovakian', 'nationality_id' => '164'],
            ['id' => '162', 'nationality' => 'Slovenian', 'nationality_id' => '165'],
            ['id' => '163', 'nationality' => 'Solomon Islander', 'nationality_id' => '166'],
            ['id' => '164', 'nationality' => 'Somali', 'nationality_id' => '167'],
            ['id' => '165', 'nationality' => 'South African', 'nationality_id' => '168'],
            ['id' => '166', 'nationality' => 'South Korean', 'nationality_id' => '169'],
            ['id' => '167', 'nationality' => 'Spanish', 'nationality_id' => '170'],
            ['id' => '167', 'nationality' => '', 'nationality_id' => ''],
            ['id' => '168', 'nationality' => 'Sri Lankan', 'nationality_id' => '171'],
            ['id' => '169', 'nationality' => 'Sudanese', 'nationality_id' => '172'],
            ['id' => '170', 'nationality' => 'Surinamese', 'nationality_id' => '173'],
            ['id' => '171', 'nationality' => 'Swazi', 'nationality_id' => '174'],
            ['id' => '172', 'nationality' => 'Swedish', 'nationality_id' => '175'],
            ['id' => '173', 'nationality' => 'Swiss', 'nationality_id' => '176'],
            ['id' => '174', 'nationality' => 'Syrian', 'nationality_id' => '177'],
            ['id' => '175', 'nationality' => 'Taiwanese', 'nationality_id' => '178'],
            ['id' => '176', 'nationality' => 'Tajik', 'nationality_id' => '179'],
            ['id' => '177', 'nationality' => 'Tanzanian', 'nationality_id' => '180'],
            ['id' => '178', 'nationality' => 'Thai', 'nationality_id' => '181'],
            ['id' => '179', 'nationality' => 'Togolese', 'nationality_id' => '182'],
            ['id' => '180', 'nationality' => 'Tongan', 'nationality_id' => '183'],
            ['id' => '181', 'nationality' => 'Trinidadian or Tobagonian', 'nationality_id' => '184'],
            ['id' => '182', 'nationality' => 'Tunisian', 'nationality_id' => '185'],
            ['id' => '183', 'nationality' => 'Turkish', 'nationality_id' => '186'],
            ['id' => '184', 'nationality' => 'Tuvaluan', 'nationality_id' => '187'],
            ['id' => '185', 'nationality' => 'Ugandan', 'nationality_id' => '188'],
            ['id' => '186', 'nationality' => 'Ukrainian', 'nationality_id' => '189'],
            ['id' => '187', 'nationality' => 'Uruguayan', 'nationality_id' => '190'],
            ['id' => '188', 'nationality' => 'Uzbekistani', 'nationality_id' => '191'],
            ['id' => '189', 'nationality' => 'Venezuelan', 'nationality_id' => '192'],
            ['id' => '190', 'nationality' => 'Vietnamese', 'nationality_id' => '193'],
            ['id' => '191', 'nationality' => 'Welsh', 'nationality_id' => '194'],
            ['id' => '192', 'nationality' => 'Yemenite', 'nationality_id' => '195'],
            ['id' => '193', 'nationality' => 'Zambian', 'nationality_id' => '196'],
            ['id' => '194', 'nationality' => 'Zimbabwean', 'nationality_id' => '197'],
            ['id' => '196', 'nationality' => 'Virgin Islands (British)', 'nationality_id' => ''],
            ['id' => '197', 'nationality' => 'Virgin Islands (USA)', 'nationality_id' => ''],
            ['id' => '198', 'nationality' => 'Islas Canaria', 'nationality_id' => ''],
            ['id' => '199', 'nationality' => 'Monegasque', 'nationality_id' => ''],
            ['id' => '200', 'nationality' => 'Vatican City', 'nationality_id' => '215'],
            ['id' => '201', 'nationality' => 'Balearic Islands', 'nationality_id' => ''],
            ['id' => '202', 'nationality' => 'Islas Canaria', 'nationality_id' => ''],
            ['id' => '203', 'nationality' => 'Guadaloupe', 'nationality_id' => ''],
            ['id' => '204', 'nationality' => 'Zairean', 'nationality_id' => ''],
            ['id' => '205', 'nationality' => 'Bermuda', 'nationality_id' => ''],
            ['id' => '206', 'nationality' => 'Reunion', 'nationality_id' => ''],
            ['id' => '207', 'nationality' => 'Vanuatuan', 'nationality_id' => ''],
            ['id' => '208', 'nationality' => 'Azores', 'nationality_id' => ''],
            ['id' => '209', 'nationality' => 'Faroese', 'nationality_id' => ''],
            ['id' => '210', 'nationality' => 'Gibraltar', 'nationality_id' => ''],
            ['id' => '211', 'nationality' => 'Guamanian', 'nationality_id' => ''],
            ['id' => '212', 'nationality' => 'Madeira', 'nationality_id' => ''],
            ['id' => '213', 'nationality' => 'Martiniquais', 'nationality_id' => ''],
            ['id' => '214', 'nationality' => 'Puerto Rico', 'nationality_id' => ''],
            ['id' => '215', 'nationality' => 'West Indian', 'nationality_id' => ''],
            ['id' => '216', 'nationality' => 'Turkmen', 'nationality_id' => '214'],
            ['id' => '217', 'nationality' => 'Dominica', 'nationality_id' => ''],
            ['id' => '218', 'nationality' => 'Nigerian', 'nationality_id' => ''],
            ['id' => '219', 'nationality' => 'Schengenian', 'nationality_id' => ''],
            ['id' => '220', 'nationality' => 'Crimean and Sevastopolian', 'nationality_id' => ''],
            ['id' => '221', 'nationality' => 'Turks and Caicos Islander', 'nationality_id' => ''],
            ['id' => '222', 'nationality' => 'Wallisian, Futunan', 'nationality_id' => ''],
            ['id' => '223', 'nationality' => 'Western Saharan', 'nationality_id' => ''],
            ['id' => '224', 'nationality' => 'Kosovar', 'nationality_id' => ''],
            ['id' => '225', 'nationality' => 'Montenegrin', 'nationality_id' => '211'],
            ['id' => '226', 'nationality' => 'Anguillan', 'nationality_id' => ''],
            ['id' => '227', 'nationality' => 'Bermudian', 'nationality_id' => '207'],
            ['id' => '228', 'nationality' => 'Botswanan', 'nationality_id' => ''],
            ['id' => '229', 'nationality' => 'Cayman Islander', 'nationality_id' => '209'],
            ['id' => '230', 'nationality' => 'Citizen of the Dominican Republic', 'nationality_id' => ''],
            ['id' => '231', 'nationality' => 'Cook Islander', 'nationality_id' => ''],
            ['id' => '232', 'nationality' => 'Faroese', 'nationality_id' => ''],
            ['id' => '233', 'nationality' => 'Greenlandic', 'nationality_id' => ''],
            ['id' => '234', 'nationality' => 'Hong Konger', 'nationality_id' => ''],
            ['id' => '235', 'nationality' => 'Kosovan', 'nationality_id' => '213'],
            ['id' => '236', 'nationality' => 'Macanese', 'nationality_id' => '210'],
            ['id' => '237', 'nationality' => 'Montserratian', 'nationality_id' => ''],
            ['id' => '238', 'nationality' => 'Niuean', 'nationality_id' => ''],
            ['id' => '239', 'nationality' => 'Pitcairn Islander', 'nationality_id' => ''],
            ['id' => '240', 'nationality' => 'Prydeinig', 'nationality_id' => ''],
            ['id' => '241', 'nationality' => 'South Sudanese', 'nationality_id' => ''],
            ['id' => '242', 'nationality' => 'St Helenian', 'nationality_id' => ''],
            ['id' => '243', 'nationality' => 'St Lucian', 'nationality_id' => ''],
            ['id' => '244', 'nationality' => 'Tristanian', 'nationality_id' => ''],
            ['id' => '245', 'nationality' => 'Vincentian', 'nationality_id' => ''],
            ['id' => '246', 'nationality' => 'British Virgin Islander', 'nationality_id' => ''],
            ['id' => '247', 'nationality' => 'Burkinan', 'nationality_id' => ''],
            ['id' => '248', 'nationality' => 'Citizen of Antigua and Barbuda', 'nationality_id' => ''],
            ['id' => '249', 'nationality' => 'Citizen of Bosnia and Herzegovina', 'nationality_id' => ''],
            ['id' => '250', 'nationality' => 'Citizen of Kiribati', 'nationality_id' => ''],
            ['id' => '251', 'nationality' => 'Congolese (Congo)', 'nationality_id' => ''],
            ['id' => '252', 'nationality' => 'Congolese (DRC)', 'nationality_id' => ''],
            ['id' => '253', 'nationality' => 'Cymro', 'nationality_id' => ''],
            ['id' => '254', 'nationality' => 'Cymry', 'nationality_id' => ''],
            ['id' => '255', 'nationality' => 'English', 'nationality_id' => ''],
            ['id' => '256', 'nationality' => 'Great Britain', 'nationality_id' => ''],
            ['id' => '257', 'nationality' => 'United Kingdom', 'nationality_id' => '200'],
            ['id' => '258', 'nationality' => 'Portuguese', 'nationality_id' => '147'],
        ];
        foreach ($allianceNationalities as $allianceNationality) {
            $nationality = Nationality::find((int) $allianceNationality['id']);
            if ($nationality && ! empty($allianceNationality['nationality_id']) && ! $nationality->alliance_nationality_id) {
                $nationality->update(['alliance_nationality_id' => (int) $allianceNationality['nationality_id']]);
            }
        }
    }
}
