<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{{ $pdfDate['title'] }}</title>

    <style>
        @page {
            margin: 200px 0;
            padding: 150px 0 0 0;
        }

        .page-break {
            page-break-after: always;
        }

        html {
            line-height: 1.5;
            margin: 0;
            padding: 0;
        }

        body {
            line-height: 1;
            font-family: "DejaVu Sans", sans-serif;
            position: relative;
        }

        div,
        span,
        table,
        tbody,
        tfoot,
        thead,
        tr,
        th,
        td,
        blockquote,
        dl,
        dd,
        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        hr,
        figure,
        p,
        pre {
            margin: 0;
        }

        a {
            text-decoration: inherit;
        }

        b,
        strong {
            font-weight: bolder;
        }

        table {
            width: 100%;
            border-spacing: 0;
        }

        table.bordered {
            border-color: #444444;
            border-spacing: 0;
        }

        table.bordered tbody>tr>td {
            border: 1px solid #444444;
            padding: 4px 8px;
        }

        table.bordered thead>tr>th {
            border: 1px solid #444444;
        }

        .text-left {
            text-align: left;
        }

        .text-red {
            color: red;
        }

        .my-4 {
            margin: 16px 0;
        }

        .my-8 {
            margin: 56px 0;
        }

        .mb-1 {
            margin-bottom: 1rem;
        }

        .mb-2 {
            margin-bottom: 2rem;
        }

        .mb-3 {
            margin-bottom: 3rem;
        }

        .italic {
            font-style: italic;
        }

        header {
            padding: 50px;
            max-width: 90%;
            width: 100%;
            left: 3%;
            top: 0 margin: 0px auto;
            position: fixed;
        }

        main {
            max-width: 75%;
            width: 100%;
            margin: 0 auto;
            font-size: 18px;
        }

        main,
        .mt-p {
            margin-top: 140px;
        }

        footer {
            bottom: 0px;
            left: 0px;
            right: 0px;
            z-index: 10;
            max-width: 90%;
            width: 100%;
            margin: 0px auto;
            position: fixed;
        }

        .text-center {
            text-align: center;
        }

        .title {
            margin-bottom: 2rem;
        }

        .title>h3 {
            text-align: center;
            text-decoration: underline;
            margin: 1.5rem 0;
            font-size: 22px;
        }

        .table-fixed {
            width: 100%;
        }

        table thead th {
            color: white;
            background: #0063af;
            text-align: left;
            font-weight: normal;
            padding: 5px 8px;
        }

        ol,
        ul {
            margin: 0 20px 0 35px;
            text-align: justify;
        }
    </style>
</head>

<body>
    <main>
        <table>
            <tbody>
                <tr>
                    <td width="30%">
                        <p><b>Report Date</b></p>
                    </td>
                    <td>{{ $pdfDate['date'] }}</td>
                </tr>
                <tr>
                    <td>
                        <p><b>Report Time</b></p>
                    </td>
                    <td>{{ $pdfDate['time'] }}</td>
                </tr>
                <tr>
                    <td><b>Generated By</b></td>
                    <td>{{ $pdfDate['auth'] }}</td>
                </tr>
            </tbody>
        </table>
        <br />

        <table class="bordered">
            <thead>
                <tr>
                    <th colspan="2">
                        <p><b>Filter type</b></p>
                    </th>
                    <th>
                        <p><b>Selection</b></p>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td colspan="2">
                        <p><b>Line of Business</b></p>
                    </td>
                    <td>{{ $pdfDate['lob'] }}</td>
                </tr>
                <tr>
                    <td colspan="2">
                        <p><b>Start Date</b></p>
                    </td>
                    <td>{{ $pdfDate['start_date'] }}</td>
                </tr>
                <tr>
                    <td colspan="2"><b>End Date</b></td>
                    <td>{{ $pdfDate['end_date'] }}</td>
                </tr>
                <tr>
                    <td colspan="2"><b>As At Date</b></td>
                    <td>{{ $pdfDate['as_at_date'] }}</td>
                </tr>
                <tr>
                    <td colspan="2"><b>Display By</b></td>
                    <td>{{ $pdfDate['display_by']}}</td>
                </tr>
            </tbody>
        </table>
        <br />

        @if ($pdfDate['display_by_column'])
            <div>
                <b> Display By : {{$pdfDate['display_by']}}</b>
            </div>
        @endif

        <br/>
        <table class="bordered">
            <thead>
                <tr>>
                    @if ($pdfDate['display_by_column'])
                        <th>
                            <p><b>{{$pdfDate['display_by']}}</b></p>
                        </th>
                    @else
                        <th><b>Total</b></th>
                    @endif
                    <th>
                        <p><b>Gross Conversion</b></p>
                    </th>
                    <th>
                        <p><b>Net Conversion</b></p>
                    </th>
                </tr>
            </thead>
            <tbody>
                @if (count($pdfDate['report_data']) > 0)
                    @foreach ($pdfDate['report_data'] as $row)
                        <tr>
                            @if ($pdfDate['display_by_column'])
                                <td>
                                    {{$row[$pdfDate['display_by_column']]}}
                                </td>
                            @else
                                <td></td>
                            @endif
                            <td>{{$row['gross_conversion']}} %</td>
                            <td>{{$row['net_conversion']}} %</td>
                        </tr>
                    @endforeach
                    <tr>
                        <td><b>Total</b></td>
                        <td>{{$pdfDate['total_gross_conversion']}} %</td>
                        <td>{{$pdfDate['total_net_conversion']}} %</td>
                    </tr>
                @else
                    <tr>
                        <td colspan="3" class="text-center">No data found</td>
                    </tr>
                @endif
            </tbody>
        </table>
        <br />
    </main>
</body>

</html>
