<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

/**
 * @method static static OptionOne()
 * @method static static OptionTwo()
 * @method static static OptionThree()
 */
final class ApplicationStorageEnums extends Enum
{
    public const ACTIVE = 1;
    public const INACTIVE = 0;
    public const CAR_LEAD_ALLOCATION_JOB_SWITCH = 'CAR_LEAD_ALLOCATION_JOB_SWITCH';
    public const CAR_LEAD_ALLOCATION_START_TIME = 'CAR_LEAD_ALLOCATION_START_TIME';
    public const SATURDAY_CAP_RESET_TIME = 'SATURDAY_CAP_RESET_TIME';
    public const NORMAL_CAP_RESET_TIME = 'NORMAL_CAP_RESET_TIME';
    public const CAR_LEAD_ALLOCATION_MASTER_SWITCH = 'CAR_LEAD_ALLOCATION_MASTER_SWITCH';
    public const SIB_CAR_DRIP_LIST_ID = 'SIB_CAR_DRIP_LIST_ID';
    public const SIB_HEALTH_EBP_LIST_ID = 'SIB_HEALTH_EBP_LIST_ID';
    public const RENEWAL_ALLOCATION_LEAD_EMAIL_CC = 'RENEWAL_ALLOCATION_LEAD_EMAIL_CC';
    public const HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS = 'HEALTH_MANUAL_ASSIGNMENT_USER_BYPASS';
    public const LMS_INTRO_EMAIL_BCC = 'LMS_INTRO_EMAIL_BCC';
    public const TIER_ASSIGNMENT_SWITCH = 'TIER_ASSIGNMENT_SWITCH';
    public const LMS_INTRO_EMAIL_ATTACHMENT_URL = 'LMS_INTRO_EMAIL_ATTACHMENT_URL';
    public const TIER_ASSIGNMENT_PROCESS_START_DATE = 'TIER_ASSIGNMENT_PROCESS_START_DATE';
    public const CAR_LEAD_PICKUP_FIFO = 'CAR_LEAD_PICKUP_FIFO';
    public const CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS = 'CAR_LEAD_ALLOCATION_START_DATE_FOR_LEADS';
    public const JOB_FAILED_EMAIL_RECIPIENTS = 'ahsan.ashfaq@myalfred.com,hussain.fakhruddin@insurancemarket.ae,daniyal.shahid@myalfred.com,faisal.abbas@myalfred.com,afzal.khan@myalfred.com';
    public const CAR_SOLD_STATUS_REJECTION_TEMPLATE = 'CAR_SOLD_STATUS_REJECTION_TEMPLATE';
    public const UNCONTACTABLE_STATUS_REJECTION_TEMPLATE = 'UNCONTACTABLE_STATUS_REJECTION_TEMPLATE';
    public const CAR_SOLD_RESUBMISSIONS_TEMPLATE = 'CAR_SOLD_RESUBMISSIONS_TEMPLATE';
    public const UNCON_RENEWALS_REMINDER_TEMPLATE = 'UNCON_RENEWALS_REMINDER_TEMPLATE';
    public const CAR_SOLD_RESUBMISSIONS_TO = 'CAR_SOLD_RESUBMISSIONS_TO';
    public const CAR_SOLD_RESUBMISSIONS_CC = 'CAR_SOLD_RESUBMISSIONS_CC';
    public const CAR_LOST_REJECTION_EMAIL_CC = 'CAR_LOST_REJECTION_EMAIL_CC';
    public const VAT_VALUE = 'VAT_VALUE';
    public const USER_INACTIVE_THRESHOLD = 'USER_INACTIVE_THRESHOLD';
    public const CAR_LEAD_ALLOCATION_END_TIME = 'CAR_LEAD_ALLOCATION_END_TIME';
    public const QUOTE_ALLOCATION_SWITCH = 'QUOTE_ALLOCATION_SWITCH';
    public const REASSIGNMENT_START_TIME = 'REASSIGNMENT_START_TIME';
    public const REASSIGNMENT_END_TIME = 'REASSIGNMENT_END_TIME';
    public const ENABLE_AUTO_FOLLOWUP = 'ENABLE_AUTO_FOLLOWUP';
    public const APPLY_DUBAI_NOW_EXCLUSION = 'APPLY_DUBAI_NOW_EXCLUSION';
    public const ENABLE_CAMMY_FOLLOWUP = 'ENABLE_CAMMY_FOLLOWUP';
    public const OCB_NEW_BUSINESS_MULTIPLE_PLANS = 'OCB_NEW_BUSINESS_MULTIPLE_PLANS';
    public const OCB_NEW_BUSINESS_ZERO_PLAN = 'OCB_NEW_BUSINESS_ZERO_PLAN';
    public const OCB_NEW_BUSINESS_SINGLE_PLAN = 'OCB_NEW_BUSINESS_SINGLE_PLAN';
    public const DTT_HEALTH_INITIAL_AND_FOLLOWUP_TEMPLATE = 'DTT_HEALTH_INITIAL_AND_FOLLOWUP_TEMPLATE';
    public const DTT_HEALTH_INITIAL_WITHOUT_HEALTH_TEAM = 'DTT_HEALTH_INITIAL_WITHOUT_HEALTH_TEAM';
    public const DTT_HEALTH_FOLLOWUP_AFTER_TWO_DAYS_WITHOUT_HEALTH_TEAM = 'DTT_HEALTH_FOLLOWUP_AFTER_TWO_DAYS_WITHOUT_HEALTH_TEAM';
    public const DTT_HEALTH_FOLLOWUP_AFTER_FOUR_DAYS_WITHOUT_HEALTH_TEAM = 'DTT_HEALTH_FOLLOWUP_AFTER_FOUR_DAYS_WITHOUT_HEALTH_TEAM';
    public const DTT_HEALTH_FOLLOWUP_AFTER_SIX_DAYS_WITHOUT_HEALTH_TEAM = 'DTT_HEALTH_FOLLOWUP_AFTER_SIX_DAYS_WITHOUT_HEALTH_TEAM';
    public const DTT_AFTER_TWO_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWO_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITHOUT_PLAN = 'DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITHOUT_PLAN';
    public const DTT_AFTER_TWO_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWO_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_SEVEN_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_THIRTEEN_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWENTY_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITH_PLAN = 'DTT_AFTER_TWENTYEIGHT_DAYS_FOLLOWUP_WITH_PLAN';
    public const DTT_HEALTH_FOLLOWUP_FROM_EMAIL = 'DTT_HEALTH_FOLLOWUP_FROM_EMAIL';
    public const ENABLE_LEAD_REASSIGNMENT = 'ENABLE_LEAD_REASSIGNMENT';
    public const DUBAI_NOW_CC_GROUP = 'DUBAI_NOW_CC_GROUP';
    public const SAGE_ENABLED = 'SAGE_ENABLED';
    public const SAGE_TIMEOUT_RETRY_ENABLED = 'SAGE_TIMEOUT_RETRY_ENABLED';
    public const DTT_ENABLED = 'DTT_ENABLED';
    public const DTT_ADVISOR = 'DTT_ADVISOR';
    public const DTT_REPLY_TO = 'DTT_REPLY_TO';
    public const DTT_HEALTH_ENABLED = 'DTT_HEALTH_ENABLED';
    public const DTT_HEALTH_REPLY_TO = 'DTT_HEALTH_REPLY_TO';
    public const ENABLE_PLAN_MODIFY_VALIDATION = 'ENABLE_PLAN_MODIFY_VALIDATION';
    public const EP_MDX_V2_FROM = 'EP_MDX_V2_FROM';
    public const EP_MDX_V3_FROM = 'EP_MDX_V3_FROM';
    public const ADVISOR_ONLINE_NOTIFICATION_EMAILS_ENABLE = 'ADVISOR_ONLINE_NOTIFICATION_EMAILS_ENABLE';
    public const EMAIL_CAMPAIGN = 'EMAIL_CAMPAIGN';
    public const INVITATION_EMAIL_TEMPLATE_FOR_CAMPAIGN = 'INVITATION_EMAIL_TEMPLATE_FOR_CAMPAIGN';
    public const CAR_BOOK_POLICY_TEMPLATE = 'CAR_BOOK_POLICY_TEMPLATE';
    public const TRAVEL_BOOK_POLICY_TEMPLATE = 'TRAVEL_BOOK_POLICY_TEMPLATE';
    public const BIKE_BOOK_POLICY_TEMPLATE = 'BIKE_BOOK_POLICY_TEMPLATE';
    public const HEALTH_BOOK_POLICY_TEMPLATE = 'HEALTH_BOOK_POLICY_TEMPLATE';
    public const LIFE_BOOK_POLICY_TEMPLATE = 'LIFE_BOOK_POLICY_TEMPLATE';
    public const HOME_BOOK_POLICY_TEMPLATE = 'HOME_BOOK_POLICY_TEMPLATE';
    public const PET_BOOK_POLICY_TEMPLATE = 'PET_BOOK_POLICY_TEMPLATE';
    public const CYCLE_BOOK_POLICY_TEMPLATE = 'CYCLE_BOOK_POLICY_TEMPLATE';
    public const YACHT_BOOK_POLICY_TEMPLATE = 'YACHT_BOOK_POLICY_TEMPLATE';
    public const GROUP_MEDICAL_BOOK_POLICY_TEMPLATE = 'GROUP_MEDICAL_BOOK_POLICY_TEMPLATE';
    public const CORPLINE_BOOK_POLICY_TEMPLATE = 'CORPLINE_BOOK_POLICY_TEMPLATE';
    public const VAT = 0.05;
    public const QUOTE_SYNC_CLEANUP_ENABLED = 'QUOTE_SYNC_CLEANUP_ENABLED';
    public const QUOTE_SYNC_CLEANUP_DAYS = 'QUOTE_SYNC_CLEANUP_DAYS';
    public const CAR_SEND_POLICY_TEMPLATE = 'CAR_SEND_POLICY_TEMPLATE';
    public const HEALTH_SEND_POLICY_TEMPLATE = 'HEALTH_SEND_POLICY_TEMPLATE';
    public const TRAVEL_SEND_POLICY_TEMPLATE = 'TRAVEL_SEND_POLICY_TEMPLATE';
    public const LIFE_SEND_POLICY_TEMPLATE = 'LIFE_SEND_POLICY_TEMPLATE';
    public const HOME_SEND_POLICY_TEMPLATE = 'HOME_SEND_POLICY_TEMPLATE';
    public const PET_SEND_POLICY_TEMPLATE = 'PET_SEND_POLICY_TEMPLATE';
    public const CYCLE_SEND_POLICY_TEMPLATE = 'CYCLE_SEND_POLICY_TEMPLATE';
    public const BIKE_SEND_POLICY_TEMPLATE = 'BIKE_SEND_POLICY_TEMPLATE';
    public const YACHT_SEND_POLICY_TEMPLATE = 'YACHT_SEND_POLICY_TEMPLATE';
    public const CORPLINE_CAR_SEND_POLICY_TEMPLATE = 'CORPLINE_CAR_SEND_POLICY_TEMPLATE';
    public const CORPLINE_TRADE_SEND_POLICY_TEMPLATE = 'CORPLINE_TRADE_SEND_POLICY_TEMPLATE';
    public const GROUP_MEDICAL_SEND_POLICY_TEMPLATE = 'GROUP_MEDICAL_SEND_POLICY_TEMPLATE';
    public const IM_EB_SERVICE_TEAM_EMAIL = 'IM_EB_SERVICE_TEAM_EMAIL';
    public const SEND_UPDATE_EMAIL = 'SEND_UPDATE_EMAIL';
    public const SEND_POLICY_UPDATE_EMAIL = 'SEND_POLICY_UPDATE_EMAIL';
    public const ALFRED_FOLLOWUP_TEMPLATE = 'ALFRED_FOLLOWUP_TEMPLATE';
    public const PAYMENT_NOTIFICATION_EMAIL_TEMPLATE = 'PAYMENT_NOTIFICATION_EMAIL_TEMPLATE';
    public const SIC_FOLLOWUP_TEMPLATE_ID = 'SIC_FOLLOWUP_TEMPLATE_ID';
    public const BRIDGER_PASSWORD = 'BRIDGER_PASSWORD';
    public const HEALTH_OCB_EMAIL_TEMPLATE = 'HEALTH_OCB_EMAIL_TEMPLATE';
    public const EMAIL_CAMPAIGN_ENABLED = 'EMAIL_CAMPAIGN_ENABLED';
    public const ALFRED_PROTECT_BOOK_POLICY_TEMPLATE = 'ALFRED_PROTECT_BOOK_POLICY_TEMPLATE';
    public const SUKOON_PAYMENT_GATEWAY = 'SUKOON_PAYMENT_GATEWAY';
    public const SUKOON_PRODUCT_SLUG = 'SUKOON_PRODUCT_SLUG';
    public const SUKOON_TEMPLATE_POLICY_CERTIFICATE = 'SUKOON_TEMPLATE_POLICY_CERTIFICATE';
    public const SUKOON_TEMPLATE_TAX_CREDIT = 'SUKOON_TEMPLATE_TAX_CREDIT';
    public const SUKOON_TEMPLATE_TAX_CREDIT_BUYER = 'SUKOON_TEMPLATE_TAX_CREDIT_BUYER';
    public const SUKOON_TEMPLATE_TAX_INVOICE = 'SUKOON_TEMPLATE_TAX_INVOICE';
    public const SUKOON_TEMPLATE_TAX_INVOICE_BUYER = 'SUKOON_TEMPLATE_TAX_INVOICE_BUYER';
    public const LEAD_SOURCE_ECOMMERCE = 'LEAD_SOURCE_ECOMMERCE';
    public const FAKE_LEAD_DOMAINS = 'FAKE_LEAD_DOMAINS';

    // Travel SIC 2.0
    public const SIC_TRAVEL_WORKFLOW_ENABLE = 'SIC_TRAVEL_WORKFLOW_ENABLE';
    public const SIC_TRAVEL_WORKFLOW_DISABLE = 'SIC_TRAVEL_WORKFLOW_DISABLE';
    public const TRAVEL_EMAIL_TEMPLATE = 'TRAVEL_EMAIL_TEMPLATE';
    public const SIC_TRAVEL_FOLLOWUP_TEMPLATE_ID = 'SIC_TRAVEL_FOLLOWUP_TEMPLATE_ID';
    public const SIC_TRAVEL_EMAIL_CC = 'SIC_TRAVEL_EMAIL_CC';
    public const TRAVEL_EMAIL_REPLY_TO = 'TRAVEL_EMAIL_REPLY_TO';
    public const DIS_INBOX_EMAIL_BCC = 'DIS_INBOX_EMAIL_BCC';
    public const BIRD_SIC_HEALTH_WORKFLOW = 'BIRD_SIC_HEALTH_WORKFLOW';

    // MOTOR RENEWAL SIC 3.0
    public const BIRD_SIC_MOTOR_RENEWAL_WORKFLOW = 'BIRD_SIC_MOTOR_RENEWAL_WORKFLOW';

    // whatsapp number for instant alfred
    public const INSTANT_ALFRED_WHATSAPP_NUMBER = 'INSTANT_ALFRED_WHATSAPP_NUMBER';

    // Health Plan Insurer Provider For Send & Book Policy
    public const BUP_HEALTH_DOC = 'BUP_HEALTH_DOC';
    public const OIC_HEALTH_DOC = 'OIC_HEALTH_DOC';
    public const AXA_HEALTH_DOC = 'AXA_HEALTH_DOC';
    public const DIC_HEALTH_DOC = 'DIC_HEALTH_DOC';
    public const CIG_HEALTH_DOC = 'CIG_HEALTH_DOC';
    public const ALLIANZ_HEALTH_DOC = 'ALLIANZ_HEALTH_DOC';

    // Health Network For Send & Book Policy
    public const MEDNET_HEALTH_DOC = 'MEDNET_HEALTH_DOC';
    public const NEXTCARE_HEALTH_DOC = 'NEXTCARE_HEALTH_DOC';
    public const NAS_HEALTH_DOC = 'NAS_HEALTH_DOC';
    public const E_CARE_HEALTH_DOC = 'E_CARE_HEALTH_DOC';
    public const INSLY_M2_RELEASE_DATE = 'INSLY_M2_RELEASE_DATE';
    public const BIRD_WORKSPACE_ID = 'BIRD_WORKSPACE_ID';
    public const BIRD_CHANNEL_ID = 'BIRD_CHANNEL_ID';
    public const ENABLE_PAYMENT_NOTIFICATION = 'ENABLE_PAYMENT_NOTIFICATION';
    public const ENABLE_PAYMENT_NOTIFICATION_EMAIL = 'ENABLE_PAYMENT_NOTIFICATION_EMAIL';
    public const PAYMENT_AUTHORISED_DAYS = 'PAYMENT_AUTHORISED_DAYS';
    public const ADVISOR_CONVERSION_QUOTE_STATUS_DATE = 'ADVISOR_CONVERSION_QUOTE_STATUS_DATE';
    public const BIRD_TRAVEL_FLLOWUP_DEDICATED_WORKFLOW_URL = 'BIRD_TRAVEL_FLLOWUP_DEDICATED_WORKFLOW_URL';
    public const HEALTH_APPLY_NOW_EMAIL_TEMPLATE_ID = 'HEALTH_APPLY_NOW_EMAIL_TEMPLATE_ID';
    public const BIRD_NB_MOTOR_WORKFLOW = 'BIRD_NB_MOTOR_WORKFLOW';
    public const CAR_EMAIL_REPLY_TO = 'CAR_EMAIL_REPLY_TO';
    public const CAR_DISPLAY_NAME = 'CAR_DISPLAY_NAME';
    public const TRAVEL_DISPLAY_NAME = 'TRAVEL_DISPLAY_NAME';
    public const HEALTH_AUTOMATED_FOLLOWUPS_SWITCH = 'HEALTH_AUTOMATED_FOLLOWUPS_SWITCH';
    public const BIRD_ACCESS_KEY = 'BIRD_ACCESS_KEY';
    public const HOME_VALUE_ADVISORS = 'HOME_VALUE_ADVISORS';
    public const HOME_VOLUME_ADVISORS = 'HOME_VOLUME_ADVISORS';
    public const IS_CAMPAIGN = 'IS_CAMPAIGN';
    public const NB_MOTOR_FOLLOWUP_DELAY_DURATION = 'NB_MOTOR_FOLLOWUP_DELAY_DURATION';
    public const BIRD_TRAVEL_RENEWALS_OCB = 'BIRD_TRAVEL_RENEWALS_OCB';
    public const COURIER_QUOTES_SYNC_ENABLED = 'COURIER_QUOTES_SYNC_ENABLED';
    public const PROCESS_CC_PAYMENTS_ENABLED = 'PROCESS_CC_PAYMENTS_ENABLED';
    public const TRAVEL_RENEWALS_SWITCH = 'TRAVEL_RENEWALS_SWITCH';

    /* Policy Issuance Automation */
    public const ENABLE_ALLIANCE_TRAVEL_POLICY_ISSUANCE = 'ENABLE_ALLIANCE_TRAVEL_POLICY_ISSUANCE';
    public const ENABLE_RETRY_TIMEOUT_ALLIANCE_TRAVEL_POLICY_ISSUANCE = 'ENABLE_RETRY_TIMEOUT_ALLIANCE_TRAVEL_POLICY_ISSUANCE';
    public const TRAVEL_ALLIANCE_FAILED_ALLOCATION_EMAIL_EVENT_URL = 'TRAVEL_ALLIANCE_FAILED_ALLOCATION_EMAIL_EVENT_URL';
    public const HOME_OCB_AUTOMATED_FOLLOWUPS = 'HOME_OCB_AUTOMATED_FOLLOWUPS';
    public const HOME_OCB_AUTOMATED_FOLLOWUPS_SWITCH = 'HOME_OCB_AUTOMATED_FOLLOWUPS_SWITCH';
    public const BIRD_WHATSAPP_NO_PLANS_ASSIGNMENT_WORKFLOW = 'BIRD_WHATSAPP_NO_PLANS_ASSIGNMENT_WORKFLOW';
    public const PUBLIC_HOLIDAY_START_DATE = 'PUBLIC_HOLIDAY_START_DATE';
    public const PUBLIC_HOLIDAY_END_DATE = 'PUBLIC_HOLIDAY_END_DATE';
    public const TRAVEL_RENEWALS_DAYS_THRESHOLD = 'TRAVEL_RENEWALS_DAYS_THRESHOLD';
    public const USER_UNAVAILABLE_TIME_THRESHOLD = 'USER_UNAVAILABLE_TIME_THRESHOLD';

    /* Bike LMS Intro Email BCC */
    public const LMS_INTRO_BIKE_EMAIL_BCC = 'LMS_INTRO_BIKE_EMAIL_BCC';
}
